version: '3.8'


networks:
  default:
    name: my-network
services:
  db:
    networks:
      - default 
    container_name: ecsa_postgres
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  db_migrate:
    networks:
      - default 
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://${DATABASE_USER}:${DATABASE_PASS}@${DATABASE_HOST}:${DATABASE_PORT}?sslmode=disable", "up"]
    links:
      - db
  api:
    networks:
      - default 
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      - LOAD_ENV_URL=true 
    depends_on:
      - db
      - db_migrate
    env_file:
      - .env
    links:
      - db
  app_dev:
    networks: 
      - default 
    container_name: app_air
    image: cosmtrek/air
    working_dir: /app
    ports: 
      - 8080:8080
    environment:
      - LOAD_ENV_URL=true 
    depends_on:
      - db
      - db_migrate
    volumes:
      - ./:/app/
    env_file:
      - .env
