version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker 
    ports:
      - 5432:5432
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      - LOAD_ENV_URL=true 
    depends_on:
      - db
    env_file:
      - .env
