version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker 
    ports:
      - 5432:5432
  db_migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:docker@host.docker.internal:5432?sslmode=disable", "up"]
    links:
      - db
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    environment:
      - LOAD_ENV_URL=true 
    depends_on:
      - db
      - db_migrate
    env_file:
      - .env
    links:
      - db
  app_dev:
    container_name: app_air
    image: cosmtrek/air
    working_dir: /app
    ports: 
      - 8080:8080
    environment:
      - LOAD_ENV_URL=true 
    depends_on:
      - db
      - db_migrate
    volumes:
      - ./:/app/
    env_file:
      - .env
